spring.application.name=demo
# Datos de conexión
spring.datasource.url=jdbc:postgresql://localhost:5432/helpdesk_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate para que cree las tablas solo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true